import { Ionicons } from '@expo/vector-icons';
import { Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { PrimaryButton } from '@/components/page';
import { showAppAlert } from '@/lib/app-overlay';
import { SellerShell } from '@/components/seller-shell';
import { colors, fonts, radius } from '@/constants/theme';
import { getDishImageSource } from '@/lib/food-image';
const fields = ['상품명','상품 설명','정가','판매가','판매 수량','픽업 시간'];
export default function NewDish() { return <SellerShell back title="새 상품 등록" description="등록한 이미지가 상품 상세와 장바구니에 표시돼요."><View><Text style={styles.label}>상품 이미지</Text><View style={styles.upload}><Image source={getDishImageSource({})} style={styles.uploadImage}/><View style={styles.uploadShade}/><Pressable accessibilityRole="button" onPress={() => showAppAlert('이미지 업로드 준비 중', '업로드 API 연결 전까지 더미 상품 이미지를 사용합니다.')} style={styles.uploadButton}><Ionicons name="camera-outline" size={17} color={colors.ink900}/><Text style={styles.uploadButtonText}>상품 사진 변경</Text></Pressable></View><Text style={styles.helper}>대표 사진 한 장이 상품 상세와 장바구니에 동일하게 표시돼요.</Text></View><Text style={styles.label}>카테고리</Text><Text style={styles.categories}>양식　 한식　 베이커리　 음료</Text>{fields.map((x)=><TextInput key={x} placeholder={x} placeholderTextColor={colors.ink400} style={styles.input} />)}<PrimaryButton label="상품 등록" /></SellerShell>; }
const styles=StyleSheet.create({ upload:{position:'relative',height:170,overflow:'hidden',backgroundColor:colors.canvas,borderWidth:1,borderColor:colors.lineStrong,borderRadius:radius.card},uploadImage:{width:'100%',height:'100%'},uploadShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.08)'},uploadButton:{position:'absolute',right:12,bottom:12,minHeight:40,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:6,borderRadius:radius.control,backgroundColor:'rgba(255,255,255,.94)'},uploadButtonText:{color:colors.ink900,fontFamily:fonts.body,fontSize:12,fontWeight:'900'},helper:{marginTop:7,color:colors.ink500,fontFamily:fonts.body,fontSize:10,lineHeight:15},label:{color:colors.ink900,fontFamily:fonts.body,fontWeight:'900'},categories:{padding:14,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radius.input,color:colors.ink700},input:{height:54,paddingHorizontal:14,color:colors.ink900,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radius.input}});
