CREATE TABLE public.presigned_uploads (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id bigint NOT NULL,
    content_length bigint NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    resource_type character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    content_type character varying(100) NOT NULL,
    object_key character varying(512) NOT NULL,
    CONSTRAINT presigned_uploads_pkey PRIMARY KEY (id),
    CONSTRAINT uk_presigned_uploads_object_key UNIQUE (object_key),
    CONSTRAINT presigned_uploads_content_length_check CHECK (content_length > 0),
    CONSTRAINT presigned_uploads_resource_type_check
        CHECK (resource_type IN ('DISH', 'AI_IMAGE')),
    CONSTRAINT presigned_uploads_status_check
        CHECK (status IN ('PENDING', 'CONFIRMED', 'EXPIRED'))
);

CREATE INDEX idx_presigned_uploads_member_created_at
    ON public.presigned_uploads (member_id, created_at);

CREATE INDEX idx_presigned_uploads_status_expires_at
    ON public.presigned_uploads (status, expires_at);
