-- core-service의 store_favorite(매장 찜) 도메인 스키마입니다.

CREATE TABLE public.store_favorites (
                                        store_favorite_id bigint NOT NULL,
                                        member_id bigint NOT NULL,
                                        store_id bigint NOT NULL,
                                        created_at timestamp(6) without time zone NOT NULL,
                                        CONSTRAINT store_favorites_member_store_key UNIQUE (member_id, store_id)
);

ALTER TABLE public.store_favorites ALTER COLUMN store_favorite_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_favorites_store_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.store_favorites
    ADD CONSTRAINT store_favorites_pkey PRIMARY KEY (store_favorite_id);

CREATE INDEX idx_store_favorites_member_created
    ON public.store_favorites USING btree (member_id, created_at DESC);
