--
-- PostgreSQL database dump
--

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    pickup_end_at time(0) without time zone NOT NULL,
    pickup_start_at time(0) without time zone NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    cart_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    dish_id bigint NOT NULL,
    id bigint NOT NULL,
    last_applied_dish_price_version bigint DEFAULT 0 NOT NULL,
    last_applied_dish_version bigint DEFAULT 0 NOT NULL,
    quantity bigint NOT NULL,
    store_id bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    status character varying(30) NOT NULL,
    dish_name character varying(255) NOT NULL,
    CONSTRAINT cart_items_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'INSUFFICIENT_STOCK'::character varying, 'OUT_OF_STOCK'::character varying, 'DISH_UNAVAILABLE'::character varying])::text[])))
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deposit_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deposit_history (
    amount numeric(19,4) NOT NULL,
    balance_after numeric(19,4) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deposit_history_id bigint NOT NULL,
    member_id bigint NOT NULL,
    order_id bigint,
    payment_id bigint,
    type character varying(255) NOT NULL,
    CONSTRAINT deposit_history_type_check CHECK (((type)::text = ANY ((ARRAY['CHARGE'::character varying, 'USE'::character varying, 'REFUND'::character varying])::text[])))
);


--
-- Name: deposit_history_deposit_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deposit_history ALTER COLUMN deposit_history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposit_history_deposit_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deposits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deposits (
    balance numeric(19,4) NOT NULL,
    deposit_id bigint NOT NULL,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: deposits_deposit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deposits ALTER COLUMN deposit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposits_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dishes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dishes (
    discount_price numeric(38,2),
    dish_price numeric(38,2) NOT NULL,
    is_deleted boolean NOT NULL,
    pickup_end_time time(0) without time zone NOT NULL,
    pickup_start_time time(0) without time zone NOT NULL,
    event_version bigint DEFAULT 0 NOT NULL,
    id bigint NOT NULL,
    registered_at timestamp(6) without time zone NOT NULL,
    stock_quantity bigint NOT NULL,
    store_id bigint NOT NULL,
    description character varying(255) NOT NULL,
    dish_name character varying(255) NOT NULL,
    dish_status character varying(255) NOT NULL,
    thumbnail_url character varying(255),
    CONSTRAINT dishes_dish_status_check CHECK (((dish_status)::text = ANY ((ARRAY['ON_SALE'::character varying, 'SOLD_OUT'::character varying, 'CLOSED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: dishes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dishes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dishes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    is_deleted boolean NOT NULL,
    pickup_end_at time(0) without time zone NOT NULL,
    pickup_deadline timestamp(6) without time zone NOT NULL,
    pickup_start_at time(0) without time zone NOT NULL,
    total_price numeric(38,2) NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    dish_id bigint NOT NULL,
    event_version bigint DEFAULT 0 NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    quantity bigint NOT NULL,
    store_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    cancel_reason character varying(255),
    dish_name character varying(255) NOT NULL,
    member_name character varying(255),
    payment_status character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    pickup_code character varying(255),
    reject_reason character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT orders_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT orders_reject_reason_check CHECK (((reject_reason)::text = ANY ((ARRAY['OUT_OF_STOCK'::character varying, 'QUALITY_ISSUE'::character varying, 'NOT_READY'::character varying, 'STORE_CLOSED'::character varying, 'SYSTEM_ERROR'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['RESERVED'::character varying, 'PICKUP_READY'::character varying, 'PICKED_UP'::character varying, 'NO_SHOW'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: order_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_history (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    member_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    order_updated_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT order_history_status_check CHECK (((status)::text = ANY ((ARRAY['RESERVED'::character varying, 'PICKUP_READY'::character varying, 'PICKED_UP'::character varying, 'NO_SHOW'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: order_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outbox_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_events (
    retry_count integer NOT NULL,
    schema_version integer DEFAULT 1 NOT NULL,
    aggregate_id bigint NOT NULL,
    aggregate_version bigint DEFAULT 0 NOT NULL,
    locked_at timestamp(6) with time zone,
    occurred_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    event_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    event_type character varying(100) NOT NULL,
    last_error character varying(1000),
    payload text NOT NULL,
    CONSTRAINT outbox_events_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: payment_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_log (
    http_status integer,
    created_at timestamp(6) without time zone NOT NULL,
    payment_id bigint NOT NULL,
    payment_log_id bigint NOT NULL,
    log_type character varying(255) NOT NULL,
    pg_provider character varying(255) NOT NULL,
    pg_result_code character varying(255),
    raw_payload text NOT NULL,
    CONSTRAINT payment_log_log_type_check CHECK (((log_type)::text = ANY ((ARRAY['REQUEST'::character varying, 'RESPONSE'::character varying])::text[]))),
    CONSTRAINT payment_log_pg_provider_check CHECK (((pg_provider)::text = ANY ((ARRAY['TOSS'::character varying, 'KAKAOPAY'::character varying])::text[])))
);


--
-- Name: payment_log_payment_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_log ALTER COLUMN payment_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_log_payment_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    amount numeric(38,2) NOT NULL,
    approved_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    payment_id bigint NOT NULL,
    approved_status character varying(255) NOT NULL,
    merchant_order_id character varying(255) NOT NULL,
    pg_provider character varying(255) NOT NULL,
    pg_transaction_id character varying(255),
    CONSTRAINT payments_approved_status_check CHECK (((approved_status)::text = ANY ((ARRAY['READY'::character varying, 'APPROVED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT payments_pg_provider_check CHECK (((pg_provider)::text = ANY ((ARRAY['TOSS'::character varying, 'KAKAOPAY'::character varying])::text[])))
);


--
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlement_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlement_details (
    fee_rate numeric(5,4) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    fee_amount bigint NOT NULL,
    id bigint NOT NULL,
    order_completed_at timestamp(6) without time zone NOT NULL,
    order_id bigint NOT NULL,
    sales_amount bigint NOT NULL,
    settlement_amount bigint NOT NULL,
    settlement_id bigint NOT NULL,
    CONSTRAINT settlement_details_check CHECK (((sales_amount >= 0) AND (fee_rate >= (0)::numeric) AND (fee_rate <= (1)::numeric) AND (fee_amount >= 0) AND (settlement_amount >= 0) AND (settlement_amount = (sales_amount - fee_amount))))
);


--
-- Name: settlement_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlement_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlements (
    fee_rate numeric(5,4) NOT NULL,
    settlement_month character varying(7) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    fee_amount bigint NOT NULL,
    gross_amount bigint NOT NULL,
    id bigint NOT NULL,
    period_end timestamp(6) without time zone NOT NULL,
    period_start timestamp(6) without time zone NOT NULL,
    settlement_amount bigint NOT NULL,
    store_id bigint NOT NULL,
    total_order_count bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    bank_code character varying(20) NOT NULL,
    settlement_status character varying(20) NOT NULL,
    account_holder character varying(50) NOT NULL,
    account_number character varying(100) NOT NULL,
    failure_reason character varying(500),
    CONSTRAINT settlements_check CHECK (((period_start < period_end) AND (total_order_count >= 0) AND (gross_amount >= 0) AND (fee_rate >= (0)::numeric) AND (fee_rate <= (1)::numeric) AND (fee_amount >= 0) AND (settlement_amount >= 0) AND (settlement_amount = (gross_amount - fee_amount)))),
    CONSTRAINT settlements_settlement_status_check CHECK (((settlement_status)::text = ANY ((ARRAY['PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_holidays (
    holiday_id bigint NOT NULL,
    store_id bigint NOT NULL,
    day_of_week character varying(255) NOT NULL,
    CONSTRAINT store_holidays_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: store_holidays_holiday_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_holidays ALTER COLUMN holiday_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_holidays_holiday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_payout_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_payout_accounts (
    active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    payout_account_id bigint NOT NULL,
    store_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    account_holder character varying(255) NOT NULL,
    account_number character varying(255) NOT NULL,
    bank_name character varying(255) NOT NULL
);


--
-- Name: store_payout_accounts_payout_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_payout_accounts ALTER COLUMN payout_account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_payout_accounts_payout_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stores; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stores (
    close_time time(0) without time zone NOT NULL,
    is_deleted boolean NOT NULL,
    latitude numeric(38,2) NOT NULL,
    longitude numeric(38,2) NOT NULL,
    open_time time(0) without time zone NOT NULL,
    member_id bigint NOT NULL,
    store_id bigint NOT NULL,
    business_number character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    store_address character varying(255) NOT NULL,
    store_name character varying(255) NOT NULL,
    store_phone character varying(255) NOT NULL,
    CONSTRAINT stores_category_check CHECK (((category)::text = ANY ((ARRAY['CHICKEN'::character varying, 'CHINESE'::character varying, 'BUNSIK'::character varying, 'KOREAN'::character varying, 'SOUP_STEW'::character varying, 'CUTLET_SUSHI'::character varying, 'PIZZA'::character varying, 'CAFE_DESSERT'::character varying, 'FAST_FOOD'::character varying, 'JOKBAL_BOSSAM'::character varying, 'MEAT'::character varying, 'LATE_NIGHT'::character varying, 'WESTERN'::character varying, 'ASIAN'::character varying, 'LUNCH_BOX'::character varying])::text[]))),
    CONSTRAINT stores_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying, 'STOPPED'::character varying])::text[])))
);


--
-- Name: stores_store_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stores ALTER COLUMN store_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items cart_items_cart_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_cart_id_key UNIQUE (cart_id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_member_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_member_id_key UNIQUE (member_id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: deposit_history deposit_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposit_history
    ADD CONSTRAINT deposit_history_pkey PRIMARY KEY (deposit_history_id);


--
-- Name: deposits deposits_member_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_member_id_key UNIQUE (member_id);


--
-- Name: deposits deposits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_pkey PRIMARY KEY (deposit_id);


--
-- Name: dishes dishes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dishes
    ADD CONSTRAINT dishes_pkey PRIMARY KEY (id);


--
-- Name: order_history order_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_history
    ADD CONSTRAINT order_history_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: outbox_events outbox_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (event_id);


--
-- Name: payment_log payment_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_log
    ADD CONSTRAINT payment_log_pkey PRIMARY KEY (payment_log_id);


--
-- Name: payments payments_merchant_order_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_merchant_order_id_key UNIQUE (merchant_order_id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);


--
-- Name: settlement_details settlement_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_details
    ADD CONSTRAINT settlement_details_pkey PRIMARY KEY (id);


--
-- Name: settlements settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (id);


--
-- Name: store_holidays store_holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_holidays
    ADD CONSTRAINT store_holidays_pkey PRIMARY KEY (holiday_id);


--
-- Name: store_payout_accounts store_payout_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_payout_accounts
    ADD CONSTRAINT store_payout_accounts_pkey PRIMARY KEY (payout_account_id);


--
-- Name: stores stores_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (store_id);


--
-- Name: settlement_details uk_settlement_detail_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlement_details
    ADD CONSTRAINT uk_settlement_detail_order UNIQUE (order_id);


--
-- Name: settlements uk_settlement_store_month; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT uk_settlement_store_month UNIQUE (store_id, settlement_month);


--
-- Name: idx_orders_member_deleted_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_member_deleted_created_at ON public.orders USING btree (member_id, is_deleted, created_at);


--
-- Name: idx_orders_store_deleted_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_store_deleted_created_at ON public.orders USING btree (store_id, is_deleted, created_at);


--
-- Name: idx_orders_pickup_expiration; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_orders_pickup_expiration ON public.orders USING btree (status, pickup_deadline) WHERE ((is_deleted = false) AND ((status)::text = 'PICKUP_READY'::text));


--
-- Name: idx_order_history_order_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_history_order_created_at ON public.order_history USING btree (order_id, created_at);


--
-- Name: idx_outbox_status_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_outbox_status_occurred_at ON public.outbox_events USING btree (status, occurred_at);


--
-- Name: idx_settlement_detail_settlement; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_detail_settlement ON public.settlement_details USING btree (settlement_id);


--
-- Name: idx_settlement_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_status ON public.settlements USING btree (settlement_status);


--
-- Name: idx_settlement_store_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_settlement_store_created_at ON public.settlements USING btree (store_id, created_at);


--
-- Name: order_history fk_order_history_order; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_history
    ADD CONSTRAINT fk_order_history_order FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: store_holidays fk5ag9a0mnds3cbtgyi0hjrkchu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_holidays
    ADD CONSTRAINT fk5ag9a0mnds3cbtgyi0hjrkchu FOREIGN KEY (store_id) REFERENCES public.stores(store_id);


--
-- PostgreSQL database dump complete
--
