-- core-service의 cart 도메인 스키마입니다.

CREATE TABLE public.cart_items (
    pickup_end_at time(0) without time zone,
    pickup_start_at time(0) without time zone,
    unit_price numeric(38,2) NOT NULL,
    cart_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    dish_id bigint NOT NULL,
    id bigint NOT NULL,
    last_applied_dish_price_version bigint DEFAULT 0 NOT NULL,
    last_applied_dish_version bigint DEFAULT 0 NOT NULL,
    quantity bigint NOT NULL,
    store_id bigint,
    updated_at timestamp(6) without time zone NOT NULL,
    status character varying(30) NOT NULL,
    dish_name character varying(255) NOT NULL,
    CONSTRAINT cart_items_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'INSUFFICIENT_STOCK'::character varying, 'OUT_OF_STOCK'::character varying, 'DISH_UNAVAILABLE'::character varying])::text[])))
);

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.carts (
    id bigint NOT NULL,
    member_id bigint NOT NULL
);

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_cart_id_key UNIQUE (cart_id);

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_member_id_key UNIQUE (member_id);

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);
