-- core-service의 deposit 도메인 스키마입니다.

CREATE TABLE public.deposits (
                                 balance numeric(19,2) NOT NULL,
                                 deposit_id bigint NOT NULL,
                                 member_id bigint NOT NULL,
                                 updated_at timestamp(6) without time zone NOT NULL,
                                 CONSTRAINT chk_deposits_balance_min_zero CHECK (balance >= 0)
);

ALTER TABLE public.deposits ALTER COLUMN deposit_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposits_deposit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.deposit_history (
                                        amount numeric(19,2) NOT NULL,
                                        balance_after numeric(19,2) NOT NULL,
                                        created_at timestamp(6) without time zone NOT NULL,
                                        deposit_history_id bigint NOT NULL,
                                        member_id bigint NOT NULL,
                                        order_id bigint,
                                        payment_id bigint,
                                        type character varying(255) NOT NULL,
                                        CONSTRAINT deposit_history_type_check CHECK (((type)::text = ANY ((ARRAY['CHARGE'::character varying, 'USE'::character varying, 'REFUND'::character varying])::text[]))),
    CONSTRAINT chk_deposit_history_amount_positive CHECK (amount > 0)
);

ALTER TABLE public.deposit_history ALTER COLUMN deposit_history_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposit_history_deposit_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.deposit_charge_failures (
                                                amount numeric(19,2) NOT NULL,
                                                created_at timestamp(6) without time zone NOT NULL,
                                                deposit_charge_failure_id bigint NOT NULL,
                                                member_id bigint NOT NULL,
                                                payment_id bigint NOT NULL,
                                                resolved_at timestamp(6) without time zone,
                                                status character varying(20) NOT NULL DEFAULT 'PENDING',
                                                error_message character varying(1000),
                                                CONSTRAINT chk_deposit_charge_failure_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RESOLVED'::character varying, 'IGNORED'::character varying])::text[])))
);

ALTER TABLE public.deposit_charge_failures ALTER COLUMN deposit_charge_failure_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deposit_charge_failures_deposit_charge_failure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.deposit_history
    ADD CONSTRAINT deposit_history_pkey PRIMARY KEY (deposit_history_id);

ALTER TABLE ONLY public.deposit_history
    ADD CONSTRAINT uq_deposit_history_payment_type UNIQUE (payment_id, type);

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_member_id_key UNIQUE (member_id);

ALTER TABLE ONLY public.deposits
    ADD CONSTRAINT deposits_pkey PRIMARY KEY (deposit_id);

ALTER TABLE ONLY public.deposit_charge_failures
    ADD CONSTRAINT deposit_charge_failures_pkey PRIMARY KEY (deposit_charge_failure_id);

CREATE INDEX CONCURRENTLY idx_deposit_history_member_created_at
    ON public.deposit_history (member_id, created_at DESC);

CREATE INDEX idx_deposit_charge_failures_status
    ON public.deposit_charge_failures (status, created_at);