-- core-service의 dish 도메인 스키마입니다.

CREATE TABLE public.dishes (
    discount_price numeric(38,2) NOT NULL,
    dish_price numeric(38,2) NOT NULL,
    is_deleted boolean NOT NULL,
    pickup_end_time time(0) without time zone NOT NULL,
    pickup_start_time time(0) without time zone NOT NULL,
    event_version bigint DEFAULT 0 NOT NULL,
    id bigint NOT NULL,
    registered_at timestamp(6) without time zone NOT NULL,
    stock_quantity bigint NOT NULL,
    store_id bigint NOT NULL,
    description character varying(255) NOT NULL,
    category character varying(100),
    dish_name character varying(255) NOT NULL,
    dish_status character varying(255) NOT NULL,
    thumbnail_url character varying(255),
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT dishes_dish_status_check CHECK (((dish_status)::text = ANY ((ARRAY['ON_SALE'::character varying, 'SOLD_OUT'::character varying, 'CLOSED'::character varying, 'EXPIRED'::character varying])::text[])))
);

ALTER TABLE public.dishes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dishes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.dishes
    ADD CONSTRAINT dishes_pkey PRIMARY KEY (id);
