-- core-service의 order 도메인 스키마입니다.

CREATE TABLE public.orders (
    is_deleted boolean NOT NULL,
    pickup_end_at time(0) without time zone NOT NULL,
    pickup_deadline timestamp(6) without time zone NOT NULL,
    pickup_start_at time(0) without time zone NOT NULL,
    total_price numeric(38,2) NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    dish_id bigint NOT NULL,
    event_version bigint DEFAULT 0 NOT NULL,
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    quantity bigint NOT NULL,
    store_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    cancel_reason character varying(255),
    dish_name character varying(255) NOT NULL,
    member_name character varying(255),
    payment_status character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    pickup_code character varying(255),
    reject_reason character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT orders_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT orders_reject_reason_check CHECK (((reject_reason)::text = ANY ((ARRAY['OUT_OF_STOCK'::character varying, 'QUALITY_ISSUE'::character varying, 'NOT_READY'::character varying, 'STORE_CLOSED'::character varying, 'SYSTEM_ERROR'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['RESERVED'::character varying, 'PICKUP_READY'::character varying, 'PICKED_UP'::character varying, 'NO_SHOW'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying])::text[])))
);

CREATE TABLE public.order_history (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    member_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    order_updated_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT order_history_status_check CHECK (((status)::text = ANY ((ARRAY['RESERVED'::character varying, 'PICKUP_READY'::character varying, 'PICKED_UP'::character varying, 'NO_SHOW'::character varying, 'CANCELLED'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE public.order_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.order_history
    ADD CONSTRAINT order_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

CREATE INDEX idx_orders_member_deleted_created_at ON public.orders USING btree (member_id, is_deleted, created_at);

CREATE INDEX idx_orders_store_deleted_created_at ON public.orders USING btree (store_id, is_deleted, created_at);

CREATE INDEX idx_orders_store_pickup_ready
    ON public.orders USING btree (store_id, status)
    WHERE ((is_deleted = false) AND ((status)::text = 'PICKUP_READY'::text));

CREATE INDEX idx_order_history_order_created_at ON public.order_history USING btree (order_id, created_at);

ALTER TABLE ONLY public.order_history
    ADD CONSTRAINT fk_order_history_order FOREIGN KEY (order_id) REFERENCES public.orders(id);
