-- core-service의 payment 도메인 스키마입니다.

CREATE TABLE public.payment_log (
    http_status integer,
    created_at timestamp(6) without time zone NOT NULL,
    payment_id bigint NOT NULL,
    payment_log_id bigint NOT NULL,
    log_type character varying(255) NOT NULL,
    pg_provider character varying(255) NOT NULL,
    pg_result_code character varying(255),
    raw_payload text NOT NULL,
    CONSTRAINT payment_log_log_type_check CHECK (((log_type)::text = ANY ((ARRAY['REQUEST'::character varying, 'RESPONSE'::character varying])::text[]))),
    CONSTRAINT payment_log_pg_provider_check CHECK (((pg_provider)::text = ANY ((ARRAY['TOSS'::character varying, 'KAKAOPAY'::character varying])::text[])))
);

ALTER TABLE public.payment_log ALTER COLUMN payment_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_log_payment_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payments (
    amount numeric(38,2) NOT NULL,
    approved_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    payment_id bigint NOT NULL,
    approved_status character varying(255) NOT NULL,
    merchant_order_id character varying(255) NOT NULL,
    pg_provider character varying(255) NOT NULL,
    pg_transaction_id character varying(255),
    CONSTRAINT payments_approved_status_check CHECK (((approved_status)::text = ANY ((ARRAY['READY'::character varying, 'APPROVED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT payments_pg_provider_check CHECK (((pg_provider)::text = ANY ((ARRAY['TOSS'::character varying, 'KAKAOPAY'::character varying])::text[])))
);

ALTER TABLE public.payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.payment_log
    ADD CONSTRAINT payment_log_pkey PRIMARY KEY (payment_log_id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_merchant_order_id_key UNIQUE (merchant_order_id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);
