-- core-service의 settlement 도메인 스키마입니다.

CREATE TABLE public.settlement_details (
    fee_rate numeric(5,4) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    fee_amount bigint NOT NULL,
    id bigint NOT NULL,
    order_completed_at timestamp(6) without time zone NOT NULL,
    order_id bigint NOT NULL,
    sales_amount bigint NOT NULL,
    settlement_amount bigint NOT NULL,
    settlement_id bigint NOT NULL,
    CONSTRAINT settlement_details_check CHECK (((sales_amount >= 0) AND (fee_rate >= (0)::numeric) AND (fee_rate <= (1)::numeric) AND (fee_amount >= 0) AND (settlement_amount >= 0) AND (settlement_amount = (sales_amount - fee_amount))))
);

ALTER TABLE public.settlement_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlement_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.settlements (
    fee_rate numeric(5,4) NOT NULL,
    settlement_month character varying(7) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    fee_amount bigint NOT NULL,
    gross_amount bigint NOT NULL,
    id bigint NOT NULL,
    period_end timestamp(6) without time zone NOT NULL,
    period_start timestamp(6) without time zone NOT NULL,
    settlement_amount bigint NOT NULL,
    store_id bigint NOT NULL,
    total_order_count bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    bank_code character varying(20) NOT NULL,
    settlement_status character varying(20) NOT NULL,
    account_holder character varying(50) NOT NULL,
    account_number character varying(100) NOT NULL,
    failure_reason character varying(500),
    CONSTRAINT settlements_check CHECK (((period_start < period_end) AND (total_order_count >= 0) AND (gross_amount >= 0) AND (fee_rate >= (0)::numeric) AND (fee_rate <= (1)::numeric) AND (fee_amount >= 0) AND (settlement_amount >= 0) AND (settlement_amount = (gross_amount - fee_amount)))),
    CONSTRAINT settlements_settlement_status_check CHECK (((settlement_status)::text = ANY ((ARRAY['ACCUMULATING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.settlements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.settlement_details
    ADD CONSTRAINT settlement_details_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.settlement_details
    ADD CONSTRAINT uk_settlement_detail_order UNIQUE (order_id);

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT uk_settlement_store_month UNIQUE (store_id, settlement_month);

CREATE INDEX idx_settlement_detail_settlement ON public.settlement_details USING btree (settlement_id);

CREATE INDEX idx_settlement_status ON public.settlements USING btree (settlement_status);

CREATE INDEX idx_settlement_store_created_at ON public.settlements USING btree (store_id, created_at);
