-- core-service의 store 도메인 스키마입니다.

CREATE TABLE public.store_holidays (
    holiday_id bigint NOT NULL,
    store_id bigint NOT NULL,
    day_of_week character varying(255) NOT NULL,
    CONSTRAINT store_holidays_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);

ALTER TABLE public.store_holidays ALTER COLUMN holiday_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_holidays_holiday_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.store_payout_accounts (
    active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    payout_account_id bigint NOT NULL,
    store_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    account_holder character varying(255) NOT NULL,
    account_number character varying(255) NOT NULL,
    bank_name character varying(255) NOT NULL
);

ALTER TABLE public.store_payout_accounts ALTER COLUMN payout_account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_payout_accounts_payout_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.stores (
    close_time time(0) without time zone NOT NULL,
    is_deleted boolean NOT NULL,
    latitude numeric(38,2) NOT NULL,
    longitude numeric(38,2) NOT NULL,
    open_time time(0) without time zone NOT NULL,
    member_id bigint NOT NULL,
    store_id bigint NOT NULL,
    business_number character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    store_address character varying(255) NOT NULL,
    store_name character varying(255) NOT NULL,
    store_phone character varying(255) NOT NULL,
    CONSTRAINT stores_category_check CHECK (((category)::text = ANY ((ARRAY['CHICKEN'::character varying, 'CHINESE'::character varying, 'BUNSIK'::character varying, 'KOREAN'::character varying, 'SOUP_STEW'::character varying, 'CUTLET_SUSHI'::character varying, 'PIZZA'::character varying, 'CAFE_DESSERT'::character varying, 'FAST_FOOD'::character varying, 'JOKBAL_BOSSAM'::character varying, 'MEAT'::character varying, 'LATE_NIGHT'::character varying, 'WESTERN'::character varying, 'ASIAN'::character varying, 'LUNCH_BOX'::character varying])::text[]))),
    CONSTRAINT stores_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying, 'STOPPED'::character varying])::text[])))
);

ALTER TABLE public.stores ALTER COLUMN store_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.store_holidays
    ADD CONSTRAINT store_holidays_pkey PRIMARY KEY (holiday_id);

ALTER TABLE ONLY public.store_payout_accounts
    ADD CONSTRAINT store_payout_accounts_pkey PRIMARY KEY (payout_account_id);

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (store_id);

ALTER TABLE ONLY public.store_holidays
    ADD CONSTRAINT fk5ag9a0mnds3cbtgyi0hjrkchu FOREIGN KEY (store_id) REFERENCES public.stores(store_id);
