apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.lastdish.kr
      secretName: api-lastdish-kr-tls
  rules:
    - host: api.lastdish.kr
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 80
