spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: core-service
              uri: http://core-service:8080
              predicates:
                - Path=/api/v1/carts/**,/api/v1/orders/**,/api/v1/stores/**,/api/v1/dishes/**,/api/v1/payments/**,/api/v1/settlements/**,/api/v1/deposits/**
            - id: member-service
              uri: http://member-service:8080
              predicates:
                - Path=/api/v1/auth/**,/api/v1/members/**
            - id: member-openapi
              uri: http://member-service:8080
              predicates:
                - Path=/openapi/member-service
              filters:
                - SetPath=/v3/api-docs
            - id: core-openapi
              uri: http://core-service:8080
              predicates:
                - Path=/openapi/core-service
              filters:
                - SetPath=/v3/api-docs

gateway:
  security:
    jwt:
      issuer: lastdish-member-service
      public-key-location: ${JWT_PUBLIC_KEY_LOCATION}
