server:
  port: 8080

spring:
  application:
    name: core-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      probes:
        enabled: true
