springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

swagger:
  servers:
    gateway-url: ${SWAGGER_GATEWAY_URL:http://localhost:8080}
    direct-url: ${SWAGGER_CORE_DIRECT_URL:http://localhost:8082}
  cors:
    allowed-origin: ${SWAGGER_UI_ORIGIN:http://localhost:8080}

toss:
  client-key: "test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm"
  secret-key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"