-- payment_db 내부 public 스키마에는 Payment가 소유하는 테이블만 생성합니다.
-- deposits/deposit_history와 settlements/settlement_details는 core_db에 유지합니다.

CREATE TABLE public.payments (
    amount numeric(38,2) NOT NULL,
    approved_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    payment_id bigint NOT NULL,
    approved_status character varying(255) NOT NULL,
    merchant_order_id character varying(255) NOT NULL,
    pg_provider character varying(255) NOT NULL,
    pg_transaction_id character varying(255),
    CONSTRAINT payments_approved_status_check CHECK (((approved_status)::text = ANY ((ARRAY['READY'::character varying, 'APPROVED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT payments_pg_provider_check CHECK (((pg_provider)::text = ANY ((ARRAY['TOSS'::character varying, 'KAKAOPAY'::character varying])::text[]))),
    CONSTRAINT payments_merchant_order_id_key UNIQUE (merchant_order_id),
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

ALTER TABLE public.payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payment_log (
    http_status integer,
    created_at timestamp(6) without time zone NOT NULL,
    payment_id bigint NOT NULL,
    payment_log_id bigint NOT NULL,
    log_type character varying(255) NOT NULL,
    pg_provider character varying(255) NOT NULL,
    pg_result_code character varying(255),
    raw_payload text NOT NULL,
    CONSTRAINT payment_log_log_type_check CHECK (((log_type)::text = ANY ((ARRAY['REQUEST'::character varying, 'RESPONSE'::character varying])::text[]))),
    CONSTRAINT payment_log_pg_provider_check CHECK (((pg_provider)::text = ANY ((ARRAY['TOSS'::character varying, 'KAKAOPAY'::character varying])::text[]))),
    CONSTRAINT payment_log_pkey PRIMARY KEY (payment_log_id)
);

ALTER TABLE public.payment_log ALTER COLUMN payment_log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_log_payment_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Payment 도메인 변경과 Kafka 발행을 한 트랜잭션으로 묶기 위한 전용 Outbox입니다.
CREATE TABLE public.outbox_events (
    retry_count integer NOT NULL,
    schema_version integer DEFAULT 1 NOT NULL,
    aggregate_id bigint NOT NULL,
    aggregate_version bigint DEFAULT 0 NOT NULL,
    locked_at timestamp(6) with time zone,
    occurred_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    event_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    event_type character varying(100) NOT NULL,
    last_error character varying(1000),
    payload text NOT NULL,
    CONSTRAINT outbox_events_pkey PRIMARY KEY (event_id),
    CONSTRAINT outbox_events_status_check CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'FAILED'))
);

CREATE INDEX idx_outbox_status_occurred_at
    ON public.outbox_events (status, occurred_at);

CREATE TABLE public.inbox_events (
                                     consumer_id VARCHAR(100) NOT NULL,
                                     event_id UUID NOT NULL,
                                     event_type VARCHAR(100) NOT NULL,
                                     aggregate_type VARCHAR(50) NOT NULL,
                                     aggregate_id BIGINT NOT NULL,
                                     aggregate_version BIGINT NOT NULL,
                                     schema_version INTEGER NOT NULL,
                                     payload TEXT NOT NULL,
                                     status VARCHAR(20) NOT NULL,
                                     retry_count INTEGER NOT NULL DEFAULT 0,
                                     last_error VARCHAR(1000),
                                     occurred_at TIMESTAMPTZ NOT NULL,
                                     received_at TIMESTAMPTZ NOT NULL,
                                     locked_at TIMESTAMPTZ,
                                     processed_at TIMESTAMPTZ,

                                     CONSTRAINT inbox_events_pkey
                                         PRIMARY KEY (consumer_id, event_id),

                                     CONSTRAINT inbox_events_status_check
                                         CHECK (status IN (
                                                           'RECEIVED',
                                                           'PROCESSING',
                                                           'PROCESSED',
                                                           'FAILED'
                                             ))
);

CREATE INDEX idx_inbox_status_received_at
    ON public.inbox_events (status, received_at);