--
-- PostgreSQL database dump
--

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.members (
    is_deleted boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    role character varying(20) NOT NULL,
    name character varying(50) NOT NULL,
    phone character varying(50) NOT NULL,
    user_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    CONSTRAINT members_role_check CHECK (((role)::text = ANY ((ARRAY['MEMBER'::character varying, 'SELLER'::character varying])::text[])))
);


--
-- Name: members_member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.members ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outbox_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outbox_events (
    retry_count integer NOT NULL,
    schema_version integer DEFAULT 1 NOT NULL,
    aggregate_id bigint NOT NULL,
    aggregate_version bigint DEFAULT 0 NOT NULL,
    locked_at timestamp(6) with time zone,
    occurred_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    event_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    aggregate_type character varying(50) NOT NULL,
    event_type character varying(100) NOT NULL,
    last_error character varying(1000),
    payload text NOT NULL,
    CONSTRAINT outbox_events_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'PUBLISHED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    expiry_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    token character varying(512) NOT NULL,
    email character varying(255) NOT NULL
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members members_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_email_key UNIQUE (email);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (member_id);


--
-- Name: members members_user_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_user_name_key UNIQUE (user_name);


--
-- Name: outbox_events outbox_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (event_id);


--
-- Name: refresh_tokens refresh_tokens_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_email_key UNIQUE (email);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: idx_outbox_status_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_outbox_status_occurred_at ON public.outbox_events USING btree (status, occurred_at);

CREATE TABLE public.inbox_events (
                                     consumer_id VARCHAR(100) NOT NULL,
                                     event_id UUID NOT NULL,
                                     event_type VARCHAR(100) NOT NULL,
                                     aggregate_type VARCHAR(50) NOT NULL,
                                     aggregate_id BIGINT NOT NULL,
                                     aggregate_version BIGINT NOT NULL,
                                     schema_version INTEGER NOT NULL,
                                     payload TEXT NOT NULL,
                                     status VARCHAR(20) NOT NULL,
                                     retry_count INTEGER NOT NULL DEFAULT 0,
                                     last_error VARCHAR(1000),
                                     occurred_at TIMESTAMPTZ NOT NULL,
                                     received_at TIMESTAMPTZ NOT NULL,
                                     locked_at TIMESTAMPTZ,
                                     processed_at TIMESTAMPTZ,

                                     CONSTRAINT inbox_events_pkey
                                         PRIMARY KEY (consumer_id, event_id),

                                     CONSTRAINT inbox_events_status_check
                                         CHECK (status IN (
                                                           'RECEIVED',
                                                           'PROCESSING',
                                                           'PROCESSED',
                                                           'FAILED'
                                             ))
);

CREATE INDEX idx_inbox_status_received_at
    ON public.inbox_events (status, received_at);

--
-- PostgreSQL database dump complete
--
