-- member-service의 member 도메인 스키마입니다.

CREATE TABLE public.members (
    is_deleted boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    member_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    role character varying(20) NOT NULL,
    name character varying(50) NOT NULL,
    phone character varying(50) NOT NULL,
    user_name character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    CONSTRAINT members_role_check CHECK (((role)::text = ANY ((ARRAY['MEMBER'::character varying, 'SELLER'::character varying])::text[])))
);

ALTER TABLE public.members ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_email_key UNIQUE (email);

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (member_id);

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_user_name_key UNIQUE (user_name);
