-- member-service의 auth 도메인 스키마입니다.

CREATE TABLE public.refresh_tokens (
    expiry_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    token character varying(512) NOT NULL,
    email character varying(255) NOT NULL
);

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_email_key UNIQUE (email);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
