-- member-service의 notification 도메인 스키마입니다.

CREATE TABLE public.notifications (
    notification_id bigint NOT NULL,
    member_id bigint NOT NULL,
    type character varying(100) NOT NULL,
    title character varying(255),
    body character varying(1000),
    data text,
    link_target character varying(100),
    link_id bigint,
    read_yn boolean NOT NULL DEFAULT false,
    event_id uuid,
    created_at timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_event_id_key UNIQUE (event_id);

CREATE INDEX idx_notifications_member_id
    ON public.notifications (member_id);

CREATE INDEX idx_notifications_member_read
    ON public.notifications (member_id, read_yn);