#server:
#  port: 8888
#
#spring:
#  application:
#    name: config-server
#  profiles:
#    default: git
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      probes:
#        enabled: true


server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native  # default 또는 active를 native로 설정

  cloud:
    config:
      server:
        native:
          search-locations: file:./infra/local/config  # 본인의 설정 파일 위치에 맞게 경로 확인

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true