import { AgreementWidget, PaymentMethodWidget, PaymentWidgetProvider, usePaymentWidget, type AgreementWidgetControl, type PaymentMethodWidgetControl } from '@tosspayments/widget-sdk-react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { colors, fonts, radius } from '@/constants/theme';
import { ConfirmModal } from '@/components/confirm-modal';
import { showAppAlert } from '@/lib/app-overlay';
import { approveDepositPayment } from '@/lib/account';
import { useAuth } from '@/providers/auth-provider';

export default function DepositPaymentScreen() {
  const params = useLocalSearchParams<{ clientKey: string; orderId: string; amount: string }>();
  const [customerKey] = useState(() => `lastdish-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`);
  return <PaymentWidgetProvider clientKey={params.clientKey} customerKey={customerKey}><PaymentContent orderId={params.orderId} amount={Number(params.amount)} /></PaymentWidgetProvider>;
}

function PaymentContent({ orderId, amount }: { orderId: string; amount: number }) {
  const widget = usePaymentWidget(); const { member } = useAuth();
  const [method, setMethod] = useState<PaymentMethodWidgetControl | null>(null); const [agreement, setAgreement] = useState<AgreementWidgetControl | null>(null); const [processing, setProcessing] = useState(false); const [confirming,setConfirming]=useState(false);
  const requestPaymentConfirmation=async()=>{if(!method||!agreement)return showAppAlert('결제창 준비 중이에요','잠시 후 다시 눌러주세요.');const status=await agreement.getAgreementStatus();if(!status.agreedRequiredTerms)return showAppAlert('약관 동의가 필요해요');setConfirming(true)};
  const pay = async () => { try { if (!method || !agreement) return showAppAlert('결제창 준비 중이에요', '잠시 후 다시 눌러주세요.'); const status = await agreement.getAgreementStatus(); if (!status.agreedRequiredTerms) return showAppAlert('약관 동의가 필요해요'); setConfirming(false); setProcessing(true); const phone = member?.phone?.replace(/\D/g, ''); const result = await widget.requestPayment({ orderId, orderName: 'LastDish 예치금 충전', customerEmail: member?.email, customerName: member?.name, customerMobilePhone: phone && phone.length >= 8 && phone.length <= 15 ? phone : undefined, appScheme: 'lastdish://' }); if (result?.fail) throw new Error(result.fail.message); if (!result?.success) return; const approved = await approveDepositPayment(result.success.paymentKey, result.success.orderId, result.success.amount); router.replace({ pathname: '/deposits/charge/success', params: { amount: String(approved.amount), balance: String(approved.depositBalance) } }); } catch (error) { router.replace({ pathname: '/deposits/charge/fail', params: { message: error instanceof Error ? error.message : '결제를 완료하지 못했어요.', amount: String(amount) } }); } finally { setProcessing(false); } };
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><View style={styles.header}><Pressable accessibilityLabel="뒤로 가기" onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.title}>결제수단 선택</Text><View style={styles.back} /></View><ScrollView contentContainerStyle={styles.scroll}><View style={styles.summary}><Text style={styles.summaryLabel}>충전 금액</Text><Text style={styles.summaryValue}>{amount.toLocaleString()}원</Text></View><PaymentMethodWidget selector="payment-methods" onLoadEnd={() => { void widget.renderPaymentMethods('payment-methods', { value: amount, currency: 'KRW', country: 'KR' }, { variantKey: 'DEFAULT' }).then(setMethod); }} /><AgreementWidget selector="agreement" onLoadEnd={() => { void widget.renderAgreement('agreement', { variantKey: 'DEFAULT' }).then(setAgreement); }} /></ScrollView><View style={styles.footer}><Pressable disabled={processing} onPress={() => void requestPaymentConfirmation()} style={[styles.button, processing && styles.disabled]}><Text style={styles.buttonText}>{processing ? '결제 승인 중…' : `${amount.toLocaleString()}원 결제하기`}</Text></Pressable></View><ConfirmModal visible={confirming} icon="card-outline" title="충전을 진행할까요?" description={`선택한 결제수단으로 ${amount.toLocaleString()}원을 결제합니다.`} confirmLabel={`${amount.toLocaleString()}원 결제`} busy={processing} busyLabel="결제창 여는 중…" onCancel={()=>setConfirming(false)} onConfirm={()=>void pay()}/></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, header: { minHeight: 56, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, backText: { color: colors.ink900, fontSize: 38, lineHeight: 40 }, title: { color: colors.ink900, fontFamily: fonts.body, fontSize: 18, fontWeight: '700' }, scroll: { paddingBottom: 24 }, summary: { marginHorizontal: 20, marginBottom: 8, padding: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderRadius: radius.card, backgroundColor: colors.green100, borderWidth: 1, borderColor: colors.green300 }, summaryLabel: { color: colors.ink700, fontFamily: fonts.body, fontSize: 12 }, summaryValue: { color: colors.ink900, fontFamily: fonts.body, fontSize: 20, fontWeight: '700' }, footer: { padding: 12, backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.line }, button: { minHeight: 52, alignItems: 'center', justifyContent: 'center', borderRadius: radius.input, backgroundColor: colors.green300 }, disabled: { opacity: 0.5 }, buttonText: { color: colors.ink900, fontFamily: fonts.body, fontSize: 16, fontWeight: '700' } });
