springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

swagger:
  servers:
    gateway-url: ${SWAGGER_GATEWAY_URL:http://localhost:8080}
    direct-url: ${SWAGGER_MEMBER_DIRECT_URL:http://localhost:8081}
  cors:
    allowed-origin: ${SWAGGER_UI_ORIGIN:http://localhost:8080}
