springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

swagger:
  servers:
    gateway-url: ${SWAGGER_GATEWAY_URL:http://localhost:8080}
    direct-url: ${SWAGGER_MEMBER_DIRECT_URL:http://localhost:8081}
  cors:
    allowed-origin: ${SWAGGER_UI_ORIGIN:http://localhost:8080}

jwt:
  rsa:
    access-private-key-location: ${JWT_ACCESS_PRIVATE_KEY_LOCATION:file:../../../infra/local/keys/access-private-key.pem}
    access-public-key-location: ${JWT_ACCESS_PUBLIC_KEY_LOCATION:file:../../../infra/local/keys/access-public-key.pem}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 1209600