server:
  port: 8080

spring:
  application:
    name: member-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
jwt:
  rsa:
    access-private-key-location: ${JWT_ACCESS_PRIVATE_KEY_LOCATION}
    access-public-key-location: ${JWT_ACCESS_PUBLIC_KEY_LOCATION}
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 1209600
