server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,refresh
  endpoint:
    gateway:
      access: unrestricted
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
