import { Ionicons } from '@expo/vector-icons';
import { router, type Href, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Page } from '@/components/page';
import { ConfirmModal } from '@/components/confirm-modal';
import { colors, fonts, radius, shadow } from '@/constants/theme';
import { getDepositBalance } from '@/lib/account';
import { temporaryMemberStats as stats } from '@/lib/member-stats';
import { useAuth } from '@/providers/auth-provider';

export default function ProfileScreen() {
  const { member, withdraw } = useAuth();
  const [depositBalance, setDepositBalance] = useState<number | null>(null);
  const [withdrawConfirming, setWithdrawConfirming] = useState(false);
  const [withdrawing, setWithdrawing] = useState(false);
  const [withdrawError, setWithdrawError] = useState<string>();
  useFocusEffect(useCallback(() => { void getDepositBalance().then(setDepositBalance).catch(() => setDepositBalance(null)); }, []));
  const levelSpan = stats.nextLevelPickupCount - stats.currentLevelStartPickupCount;
  const progress = Math.max(0, Math.min(1, (stats.completedPickupCount - stats.currentLevelStartPickupCount) / levelSpan));
  const requestWithdrawal = async () => {
    try {
      setWithdrawing(true);
      setWithdrawError(undefined);
      await withdraw();
      setWithdrawConfirming(false);
      router.replace('/my');
    } catch (error) {
      setWithdrawError(error instanceof Error ? error.message : '탈퇴를 처리하지 못했어요. 잠시 후 다시 시도해주세요.');
    } finally {
      setWithdrawing(false);
    }
  };

  return <Page title="내 정보" description="나의 등급과 라디 활동을 한눈에 확인하세요." onClose={() => router.replace('/my')} closeLabel="마이페이지로 닫기">
    <View style={styles.levelCard}><Pressable accessibilityRole="button" accessibilityHint="등급 상세를 엽니다" onPress={() => router.push('/grades' as Href)} style={({ pressed }) => [styles.levelSummary, pressed && styles.pressed]}><View style={styles.levelTop}><View style={styles.levelIcon}><Ionicons name="leaf" size={20} color={colors.green700}/></View><View style={styles.levelCopy}><Text style={styles.grade}>{stats.grade}</Text><Text style={styles.level}>LEVEL {stats.level} · 픽업으로 성장해요</Text></View><View style={styles.pickupLink}><Text style={styles.pickupMetric}>{stats.completedPickupCount}회</Text><Ionicons name="chevron-forward" size={15} color={colors.ink400}/></View></View><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${progress * 100}%` }]}/></View><View style={styles.progressMeta}><Text style={styles.progressText}>다음 레벨까지</Text><Text style={styles.progressStrong}>{stats.nextLevelPickupCount - stats.completedPickupCount}회 픽업</Text></View></Pressable><View style={styles.memberMetrics}><View style={styles.memberMetric}><View style={styles.metricLabelRow}><Ionicons name="trending-down-outline" size={14} color={colors.green300}/><Text style={styles.metricLabel}>누적 절약</Text></View><Text style={styles.metricValue}>{stats.savedAmount.toLocaleString()}원</Text></View><View style={styles.metricDivider}/><Pressable accessibilityRole="button" accessibilityHint="포인트 상세를 엽니다" onPress={() => router.push('/points' as Href)} style={({ pressed }) => [styles.memberMetric, pressed && styles.metricPressed]}><View style={styles.metricLabelRow}><Ionicons name="sparkles-outline" size={14} color={colors.green300}/><Text style={styles.metricLabel}>현재 포인트</Text></View><View style={styles.metricValueRow}><Text style={styles.metricValue}>{stats.points.toLocaleString()}P</Text><Ionicons name="chevron-forward" size={14} color={colors.ink400}/></View></Pressable></View></View>
    <Pressable accessibilityRole="button" onPress={() => router.push('/deposits')} style={({ pressed }) => [styles.radiPay, pressed && styles.pressed]}><View style={styles.radiPayIcon}><Ionicons name="wallet-outline" size={19} color={colors.green300}/></View><View style={styles.radiPayCopy}><Text style={styles.radiPayLabel}>라디페이</Text><Text style={styles.radiPayValue}>{depositBalance === null ? '잔액 확인 중' : `${depositBalance.toLocaleString()}원`}</Text></View><View style={styles.link}><Text style={styles.linkText}>이용내역</Text><Ionicons name="chevron-forward" size={16} color={colors.ink400}/></View></Pressable>
    <View style={styles.sectionHead}><Text style={styles.sectionTitle}>기본 정보</Text><Pressable accessibilityRole="button" onPress={() => router.push('/profile/edit' as Href)} style={({ pressed }) => [styles.editButton, pressed && styles.pressed]}><Ionicons name="pencil-outline" size={14} color={colors.ink900}/><Text style={styles.editText}>정보 수정</Text></Pressable></View>
    <View style={styles.account}><Info label="이름" value={member?.name ?? '—'}/><Info label="아이디" value={member?.userName ?? '—'}/><Info label="이메일" value={member?.email ?? '—'}/><Info label="전화번호" value={member?.phone ?? '—'} last/></View>
    <View style={styles.withdrawSection}><View style={styles.withdrawCopy}><Text style={styles.withdrawTitle}>계정 관리</Text><Text style={styles.withdrawHint}>탈퇴 전 데이터 보존 범위와 재가입 제한을 확인해주세요.</Text></View><Pressable accessibilityRole="button" onPress={() => { setWithdrawError(undefined); setWithdrawConfirming(true); }} style={({ pressed }) => [styles.withdrawButton, pressed && styles.pressed]}><Text style={styles.withdrawButtonText}>회원 탈퇴</Text></Pressable></View>
    <ConfirmModal visible={withdrawConfirming} icon="person-remove-outline" title="정말 탈퇴할까요?" description={`${withdrawError ? `${withdrawError}\n\n` : ''}로그인 토큰은 즉시 무효화되고 카카오 계정 연결 해제가 요청됩니다. 계정은 탈퇴 상태와 탈퇴 일시를 보존하며, 주문·결제 등 거래 기록은 즉시 삭제되지 않습니다. 현재는 같은 아이디·이메일·카카오 계정으로 재가입할 수 없습니다.`} confirmLabel="탈퇴하기" busy={withdrawing} busyLabel="탈퇴 처리 중…" tone="danger" onCancel={() => { setWithdrawConfirming(false); setWithdrawError(undefined); }} onConfirm={() => void requestWithdrawal()}/>
  </Page>;
}

function Info({ label, value, last }: { label: string; value: string; last?: boolean }) { return <View style={[styles.info, last && styles.infoLast]}><Text style={styles.infoLabel}>{label}</Text><Text numberOfLines={1} style={styles.infoValue}>{value}</Text></View>; }

const styles = StyleSheet.create({
  levelCard: { overflow: 'hidden', paddingBottom: 12, borderRadius: radius.card, backgroundColor: colors.ink900 }, levelSummary: { padding: 17, paddingBottom: 14 }, levelTop: { flexDirection: 'row', alignItems: 'center', gap: 10 }, levelIcon: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 20, backgroundColor: colors.green100 }, levelCopy: { flex: 1 }, grade: { color: colors.white, fontFamily: fonts.body, fontSize: 17, fontWeight: '900' }, level: { marginTop: 3, color: colors.ink400, fontFamily: fonts.body, fontSize: 10, fontWeight: '800' }, pickupLink: { flexDirection: 'row', alignItems: 'center', gap: 2 }, pickupMetric: { color: colors.green300, fontFamily: fonts.body, fontSize: 18, fontWeight: '900' }, progressTrack: { height: 5, marginTop: 17, overflow: 'hidden', borderRadius: 3, backgroundColor: colors.ink700 }, progressFill: { height: 5, borderRadius: 3, backgroundColor: colors.green500 }, progressMeta: { marginTop: 7, flexDirection: 'row', justifyContent: 'space-between' }, progressText: { color: colors.ink400, fontFamily: fonts.body, fontSize: 10 }, progressStrong: { color: colors.white, fontFamily: fonts.body, fontSize: 10, fontWeight: '800' }, memberMetrics: { minHeight: 72, marginHorizontal: 12, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'stretch', borderRadius: 12, backgroundColor: colors.ink700 }, memberMetric: { flex: 1, minWidth: 0, paddingVertical: 13, justifyContent: 'center' }, metricDivider: { width: StyleSheet.hairlineWidth, marginHorizontal: 13, marginVertical: 13, backgroundColor: 'rgba(255,255,255,0.12)' }, metricLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 5 }, metricLabel: { color: colors.ink400, fontFamily: fonts.body, fontSize: 10, fontWeight: '700' }, metricValueRow: { marginTop: 5, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, metricValue: { marginTop: 5, color: colors.white, fontFamily: fonts.body, fontSize: 16, fontWeight: '900' }, metricPressed: { opacity: 0.65 },
  radiPay: { minHeight: 82, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', gap: 11, borderRadius: radius.card, backgroundColor: colors.ink900, ...shadow.card }, radiPayIcon: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: 'rgba(255,255,255,0.09)' }, radiPayCopy: { flex: 1 }, radiPayLabel: { color: colors.ink400, fontFamily: fonts.body, fontSize: 10, fontWeight: '700' }, radiPayValue: { marginTop: 4, color: colors.white, fontFamily: fonts.body, fontSize: 19, fontWeight: '900' }, link: { flexDirection: 'row', alignItems: 'center', gap: 2 }, linkText: { color: colors.ink400, fontFamily: fonts.body, fontSize: 10, fontWeight: '700' },
  sectionHead: { marginTop: 8, minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, sectionTitle: { color: colors.ink900, fontFamily: fonts.body, fontSize: 16, fontWeight: '900' }, editButton: { minHeight: 44, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: radius.control, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, editText: { color: colors.ink900, fontFamily: fonts.body, fontSize: 12, fontWeight: '800' }, account: { paddingHorizontal: 15, overflow: 'hidden', borderRadius: radius.card, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, info: { minHeight: 56, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, infoLast: { borderBottomWidth: 0 }, infoLabel: { color: colors.ink500, fontFamily: fonts.body, fontSize: 12, fontWeight: '700' }, infoValue: { maxWidth: '68%', color: colors.ink900, fontFamily: fonts.body, fontSize: 13, fontWeight: '800' }, pressed: { opacity: 0.68, transform: [{ scale: 0.98 }] },
  withdrawSection: { minHeight: 68, marginTop: 4, paddingTop: 13, flexDirection: 'row', alignItems: 'center', gap: 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.line }, withdrawCopy: { flex: 1 }, withdrawTitle: { color: colors.ink700, fontFamily: fonts.body, fontSize: 13, fontWeight: '800' }, withdrawHint: { marginTop: 4, color: colors.ink400, fontFamily: fonts.body, fontSize: 10, lineHeight: 15 }, withdrawButton: { minHeight: 44, paddingHorizontal: 13, alignItems: 'center', justifyContent: 'center', borderRadius: radius.control, borderWidth: 1, borderColor: colors.danger700, backgroundColor: colors.white }, withdrawButtonText: { color: colors.danger700, fontFamily: fonts.body, fontSize: 12, fontWeight: '900' },
});
